name: Go-Build

env:
  artifact_name: ecs2k8s

on:
  pull_request:
  workflow_call:
    outputs:
      artifact_name:
        description: "The name of the artifact"
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:

  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: mkdir -p $RUNNER_TEMP/artifacts/

    - name: Build macos
      run: |
        export GOOS=darwin
        export GOARCH=amd64
        go build -o $RUNNER_TEMP/artifacts/${{ env.artifact_name }}-$GOOS-$GOARCH
    
    - name: Build linux
      run: |
        export GOOS=linux
        export GOARCH=amd64
        go build -o $RUNNER_TEMP/artifacts/${{ env.artifact_name }}-$GOOS-$GOARCH

    - name: Upload artifact
      uses:  actions/upload-artifact@v2
      with:
        name: ${{ env.artifact_name }}
        path: ${{ runner.temp }}/artifacts/*
    
    outputs:
      artifact_name: ${{ env.artifact_name }}
      