name: Release

env:
  artifact_name: ecs2k8s

on:
  push:
    branches: [ 'releases/**' ]  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: mkdir -p $RUNNER_TEMP/artifacts/

    - name: Build macos
      run: |
        export GOOS=darwin
        export GOARCH=amd64
        go build -o $RUNNER_TEMP/artifacts/$GOOS-$GOARCH/${{ env.artifact_name }}
        cd $RUNNER_TEMP/artifacts/
        zip ${{ env.artifact_name }}-$GOOS-$GOARCH.zip $GOOS-$GOARCH/${{ env.artifact_name }}
    
    - name: Build linux
      run: |
        export GOOS=linux
        export GOARCH=amd64
        go build -o $RUNNER_TEMP/artifacts/$GOOS-$GOARCH/${{ env.artifact_name }}
        cd $RUNNER_TEMP/artifacts/        
        zip ${{ env.artifact_name }}-$GOOS-$GOARCH.zip $GOOS-$GOARCH/${{ env.artifact_name }}


    - name: Create a release
      run: gh release create $GITHUB_RUN_ID ${{ env.artifact_name }} -t $GITHUB_REF_NAME ${{ runner.temp }}/artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}